import { Platform, StyleSheet } from 'react-native';
import { colors } from '../../theme/appTheme';

export const styles = StyleSheet.create({
	container: {
		flex: 1,
	},
	headerContainer: {
		flexDirection: 'row',
		paddingHorizontal: 16,
		justifyContent: 'space-between',
		alignItems: 'center',
		paddingBottom: 10,
		marginBottom: 16,
		borderBottomWidth: 1,
		borderColor: colors.crocodileTooth,
	},
	headerTitle: {
		fontSize: 18,
		fontWeight: '700',
		textTransform: 'uppercase',
		color: colors.darkCharcoal,
	},
	errorText: {
		color: colors.error,
		fontSize: 14,
		position: 'absolute',
		bottom: -19,
	},
	label: {
		fontSize: 16,
		marginBottom: 0,
		color: colors.darkCharcoal,
		textTransform: 'uppercase',
		fontWeight: '400',
	},
	selectInput: {
		display: 'flex',
		alignItems: 'center',
		marginTop: 5,
		height: Platform.OS === 'ios' ? 40 : 45,
		borderRadius: 5,
	},
	selectWidthL: {
		fontSize: 25,
	},
	input: {
		borderWidth: 1,
		borderColor: colors.crocodileTooth,
		marginTop: 5,
		height: Platform.OS === 'ios' ? 40 : 45,
		borderRadius: 5,
		fontSize: 16,
		paddingRight: 10,
		paddingLeft: 15,
	},
	inputsRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
	},
	inputContainer: {
		width: '48%',
		marginBottom: 10,
	},
	formContainer: {
		paddingHorizontal: 20,
	},
	button: {
		backgroundColor: colors.darkCharcoal,
		width: '100%',
		paddingHorizontal: 20,
		paddingVertical: 10,
		flexDirection: 'row',
		justifyContent: 'center',
		marginTop: 10,
		marginBottom: 25,
		shadowColor: colors.darkCharcoal,
		shadowOffset: { width: -2, height: 4 },
		shadowOpacity: 0.4,
		shadowRadius: 3,
		borderRadius: 5,
	},
	cancelButton: {
		backgroundColor: colors.darkCharcoal,
		width: '100%',
		paddingHorizontal: 20,
		paddingVertical: 10,
		flexDirection: 'row',
		justifyContent: 'center',
		marginTop: 10,
		marginBottom: 50,
		shadowColor: colors.darkCharcoal,
		shadowOffset: { width: -2, height: 4 },
		shadowOpacity: 0.4,
		shadowRadius: 3,
		borderRadius: 5,
	},
	buttonText: {
		textTransform: 'uppercase',
		fontSize: 16,
		fontWeight: '700',
		color: colors.cultured,
	},
	controllerContainer: {
		marginBottom: 30,
	},
});
