import { StyleSheet } from 'react-native';

import { colors } from '../../theme/appTheme';

export const styles = StyleSheet.create({
	container: {
		paddingHorizontal: 16,
		height: '100%',
	},
	button: {
		backgroundColor: colors.darkCharcoal,
		width: '100%',
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		alignSelf: 'center',
		marginTop: 25,
		paddingHorizontal: 20,
		paddingVertical: 10,
		borderRadius: 5,
		elevation: 5,
		shadowColor: colors.darkCharcoal,
		shadowOffset: { width: -2, height: 4 },
		shadowOpacity: 0.4,
		shadowRadius: 3,
	},
	buttonText: {
		textTransform: 'uppercase',
		fontSize: 16,
		fontWeight: '700',
		color: colors.cultured,
	},
	errorText: {
		color: colors.error,
		marginTop: 5,
		fontSize: 14,
		textTransform: 'uppercase',
		fontWeight: '400',
		position: 'absolute',
		bottom: -20,
	},
	googleButton: {
		width: '100%',
	},
	googleButtonContainer: {
		flexDirection: 'row',
		borderWidth: 0.5,
		borderColor: colors.crocodileTooth,
		borderRadius: 5,
		height: 45,
		alignItems: 'center',
		justifyContent: 'center',
		marginTop: 30,
		backgroundColor: colors.white,
		paddingHorizontal: 20,
		paddingVertical: 10,
		elevation: 5,
		shadowColor: colors.darkCharcoal,
		shadowOffset: { width: -1, height: 2 },
		shadowOpacity: 0.4,
		shadowRadius: 3,
	},
	googleLabel: {
		fontSize: 16,
		textTransform: 'uppercase',
		fontWeight: '700',
		color: colors.darkCharcoal,
	},
	googleIcon: {
		height: 30,
		width: 30,
		marginRight: 20,
	},
	label: {
		textTransform: 'uppercase',
		fontWeight: '400',
		fontSize: 16,
	},
	link: {
		textTransform: 'uppercase',
		fontWeight: '400',
		fontSize: 14,
		color: colors.link,
	},
	accountText: {
		textTransform: 'uppercase',
		fontWeight: '400',
		fontSize: 14,
	},
	logo: {
		width: 200,
		height: 110,
		alignSelf: 'center',
		marginTop: 20,
		marginBottom: 20,
	},
	title: {
		fontSize: 18,
		textTransform: 'uppercase',
		fontWeight: '700',
		color: colors.darkCharcoal,
	},
	input: {
		borderWidth: 1,
		borderColor: colors.crocodileTooth,
		marginTop: 5,
		height: 40,
		borderRadius: 5,
		fontSize: 16,
		paddingRight: 10,
		paddingLeft: 15,
	},
	iconContainer: {
		position: 'absolute',
		zIndex: 10,
		marginTop: 5,
		right: 0,
		height: 40,
		width: 50,
		justifyContent: 'center',
		alignItems: 'center',
	},
	inputContainer: {
		marginTop: 30,
	},
	socialAuthContainer: {
		marginTop: 30,
		marginBottom: 60,
		borderTopWidth: 1,
		borderColor: colors.crocodileTooth,
	},
	textContainer: {
		flexDirection: 'row',
		justifyContent: 'center',
		marginTop: 30,
	},
});
