import { StyleSheet } from 'react-native';
import { colors } from '../theme/appTheme';

export const styles = StyleSheet.create({
	container: {
		position: 'absolute',
		zIndex: 10,
		backgroundColor: colors.black,
		height: 16,
		width: 16,
		borderRadius: 10,
		justifyContent: 'center',
		alignItems: 'center',
		right: -6,
		top: -4,
	},
	cont600: {
		position: 'absolute',
		zIndex: 10,
		backgroundColor: colors.black,
		height: 19,
		width: 19,
		borderRadius: 15,
		justifyContent: 'center',
		alignItems: 'center',
		right: -6,
		top: -4,
	},
	cont700: {
		position: 'absolute',
		zIndex: 10,
		backgroundColor: colors.black,
		height: 22,
		width: 22,
		borderRadius: 15,
		justifyContent: 'center',
		alignItems: 'center',
		right: -6,
		top: -4,
	},
	cont800: {
		position: 'absolute',
		zIndex: 10,
		backgroundColor: colors.black,
		height: 25,
		width: 25,
		borderRadius: 15,
		justifyContent: 'center',
		alignItems: 'center',
		right: -6,
		top: -4,
	},
	cont900: {
		position: 'absolute',
		zIndex: 10,
		backgroundColor: colors.black,
		height: 28,
		width: 28,
		borderRadius: 15,
		justifyContent: 'center',
		alignItems: 'center',
		right: -6,
		top: -4,
	},
	text: {
		color: colors.white,
		fontSize: 8,
		fontWeight: '600',
	},
});
